### ISSUE TITLE
Add annotations to images after scanning

### ISSUE THREAD

**Issue by gravitypriest** [RedHatInsights/openshift-scan#5]

**Comment by brantleyr** [comment]
@gravitypriest Do we want the "controller" to control (:laughing:) the annotation portion? So the flow would be the controller spins up a scanner, gets the results from the scanner, then annotates that image?

**Comment by gravitypriest** [comment]
I think that wold be the "proper" way to do it. We may also want to consider bouncing scanner results back to the controller and handling the POST there as well.

**Comment by lphiri** [comment]
+1
Doing things in the scanner is simple in the success scenario, but doing them in the controller makes error recovery etc.. easier.
Also we want the scanner to do one job and do it well  :)
